import { MigrationInterface, QueryRunner } from "typeorm";

export class SchemaSync1770731362183 implements MigrationInterface {
    name = 'SchemaSync1770731362183'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`permissions\` (\`id\` char(36) NOT NULL, \`domain_id\` char(36) NOT NULL, \`code\` varchar(100) NOT NULL, \`name\` varchar(255) NOT NULL, \`description\` varchar(500) NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_e18b0544c532dab81b229d0d3b\` (\`domain_id\`), UNIQUE INDEX \`IDX_8dad765629e83229da6feda1c1\` (\`code\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`roles\` (\`id\` char(36) NOT NULL, \`domain_id\` char(36) NOT NULL, \`name\` varchar(100) NOT NULL, \`merchant_id\` char(36) NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_b2aef658765c9b59c454d56177\` (\`domain_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`role_permissions\` (\`role_id\` char(36) NOT NULL, \`permission_id\` char(36) NOT NULL, PRIMARY KEY (\`role_id\`, \`permission_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`users\` (\`id\` char(36) NOT NULL, \`domain_id\` char(36) NOT NULL, \`email\` varchar(255) NOT NULL, \`password_hash\` varchar(255) NOT NULL, \`full_name\` varchar(255) NOT NULL, \`merchant_id\` char(36) NOT NULL, \`role_id\` char(36) NOT NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_b07612fc9ab8c40bf34f0dcfe6\` (\`domain_id\`), UNIQUE INDEX \`IDX_97672ac88f789774dd47f7c8be\` (\`email\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`merchants\` (\`id\` char(36) NOT NULL, \`domain_id\` char(36) NOT NULL, \`shop_name\` varchar(255) NOT NULL, \`default_currency\` varchar(10) NOT NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`owner_user_id\` char(36) NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_ce3bb67cb0926240e65c08cd1b\` (\`domain_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`customers\` (\`id\` char(36) NOT NULL, \`domain_id\` char(36) NOT NULL, \`merchant_id\` char(36) NOT NULL, \`token\` varchar(64) NOT NULL, \`full_name\` varchar(255) NOT NULL, \`contact_phone\` varchar(50) NULL, \`contact_email\` varchar(255) NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_28a79a3a8385dff6fb94b4c4e9\` (\`domain_id\`), UNIQUE INDEX \`IDX_77486d71e8f68e188319c8d6ce\` (\`token\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`exchange_rates\` (\`rate_id\` char(36) NOT NULL, \`domain_id\` char(36) NOT NULL, \`merchant_id\` char(36) NOT NULL, \`base_currency\` varchar(8) NOT NULL, \`target_currency\` varchar(8) NOT NULL, \`rate_type\` varchar(8) NOT NULL, \`rate\` decimal(18,6) NOT NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`rate_date\` date NOT NULL, \`created_by\` char(36) NOT NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_f1a66c537616b14781c4cda78f\` (\`merchant_id\`, \`rate_date\`, \`base_currency\`, \`target_currency\`, \`rate_type\`), UNIQUE INDEX \`IDX_8a26668fda1abe1bd0165f0693\` (\`domain_id\`), PRIMARY KEY (\`rate_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`order_items\` (\`item_id\` char(36) NOT NULL, \`domain_id\` char(36) NOT NULL, \`order_id\` char(36) NOT NULL, \`product_name\` varchar(255) NOT NULL, \`variant\` varchar(128) NOT NULL DEFAULT '', \`quantity\` int NOT NULL, \`purchase_currency\` varchar(8) NOT NULL, \`purchase_price\` decimal(18,4) NOT NULL, \`purchase_exchange_rate\` decimal(18,6) NOT NULL, \`purchase_total_lak\` decimal(18,4) NOT NULL, \`total_cost_before_discount_lak\` decimal(18,4) NOT NULL, \`discount_type\` varchar(16) NOT NULL, \`discount_value\` decimal(18,4) NOT NULL DEFAULT '0.0000', \`discount_amount_lak\` decimal(18,4) NOT NULL DEFAULT '0.0000', \`final_cost_lak\` decimal(18,4) NOT NULL, \`final_cost_thb\` decimal(18,4) NOT NULL, \`selling_price_foreign\` decimal(18,4) NOT NULL DEFAULT '0.0000', \`selling_exchange_rate\` decimal(18,6) NOT NULL DEFAULT '0.000000', \`selling_total_lak\` decimal(18,4) NOT NULL DEFAULT '0.0000', \`profit_lak\` decimal(18,4) NOT NULL DEFAULT '0.0000', \`profit_thb\` decimal(18,4) NOT NULL DEFAULT '0.0000', \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_06168e79adf9e78a069ecbb5ba\` (\`domain_id\`), PRIMARY KEY (\`item_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`orders\` (\`order_id\` char(36) NOT NULL, \`domain_id\` char(36) NOT NULL, \`merchant_id\` char(36) NOT NULL, \`created_by\` char(36) NOT NULL, \`order_code\` varchar(64) NOT NULL, \`order_date\` date NOT NULL, \`status\` varchar(32) NOT NULL DEFAULT 'DRAFT', \`arrival_status\` varchar(32) NOT NULL, \`arrived_at\` timestamp NULL, \`notified_at\` timestamp NULL, \`total_purchase_cost_lak\` decimal(18,4) NOT NULL DEFAULT '0.0000', \`total_shipping_cost_lak\` decimal(18,4) NOT NULL DEFAULT '0.0000', \`total_cost_before_discount_lak\` decimal(18,4) NOT NULL DEFAULT '0.0000', \`total_discount_lak\` decimal(18,4) NOT NULL DEFAULT '0.0000', \`total_final_cost_lak\` decimal(18,4) NOT NULL DEFAULT '0.0000', \`total_final_cost_thb\` decimal(18,4) NOT NULL DEFAULT '0.0000', \`total_selling_amount_lak\` decimal(18,4) NOT NULL DEFAULT '0.0000', \`total_selling_amount_thb\` decimal(18,4) NOT NULL DEFAULT '0.0000', \`total_profit_lak\` decimal(18,4) NOT NULL DEFAULT '0.0000', \`total_profit_thb\` decimal(18,4) NOT NULL DEFAULT '0.0000', \`deposit_amount\` decimal(18,4) NOT NULL DEFAULT '0.0000', \`paid_amount\` decimal(18,4) NOT NULL DEFAULT '0.0000', \`remaining_amount\` decimal(18,4) NOT NULL DEFAULT '0.0000', \`payment_status\` varchar(32) NOT NULL, \`is_closed\` tinyint NOT NULL DEFAULT 0, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_06a04a826023e654bcfd58ebff\` (\`domain_id\`), PRIMARY KEY (\`order_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`customer_order_items\` (\`id\` char(36) NOT NULL, \`domain_id\` char(36) NOT NULL, \`customer_order_id\` char(36) NOT NULL, \`order_item_id\` char(36) NOT NULL, \`quantity\` int NOT NULL, \`selling_price_foreign\` decimal(18,4) NOT NULL, \`selling_total_lak\` decimal(18,4) NOT NULL, \`profit_lak\` decimal(18,4) NOT NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_c1fe570254e16ceaf3d6270d42\` (\`domain_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`customer_orders\` (\`customer_order_id\` char(36) NOT NULL, \`domain_id\` char(36) NOT NULL, \`order_id\` char(36) NOT NULL, \`customer_id\` char(36) NOT NULL, \`merchant_id\` char(36) NOT NULL, \`status\` varchar(32) NOT NULL DEFAULT 'DRAFT', \`total_selling_amount_lak\` decimal(18,4) NOT NULL DEFAULT '0.0000', \`total_paid\` decimal(18,4) NOT NULL DEFAULT '0.0000', \`remaining_amount\` decimal(18,4) NOT NULL DEFAULT '0.0000', \`payment_status\` varchar(32) NOT NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_270520ac553e98cb64f9d46a1e\` (\`domain_id\`), PRIMARY KEY (\`customer_order_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`arrival_items\` (\`arrival_item_id\` char(36) NOT NULL, \`domain_id\` char(36) NOT NULL, \`arrival_id\` char(36) NOT NULL, \`order_item_id\` char(36) NOT NULL, \`arrived_quantity\` int NOT NULL, \`condition\` varchar(16) NOT NULL DEFAULT 'OK', \`notes\` text NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_ea9d95c85f3be48768264c3d7b\` (\`domain_id\`), PRIMARY KEY (\`arrival_item_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`arrivals\` (\`arrival_id\` char(36) NOT NULL, \`domain_id\` char(36) NOT NULL, \`order_id\` char(36) NOT NULL, \`merchant_id\` char(36) NOT NULL, \`arrived_date\` date NOT NULL, \`arrived_time\` time NULL, \`recorded_by\` char(36) NOT NULL, \`notes\` text NULL, \`status\` varchar(32) NOT NULL DEFAULT 'PENDING', \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_9ca7107a9d99099330e90f21d7\` (\`domain_id\`), PRIMARY KEY (\`arrival_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`notifications\` (\`notification_id\` char(36) NOT NULL, \`domain_id\` char(36) NOT NULL, \`merchant_id\` char(36) NOT NULL, \`customer_id\` char(36) NOT NULL, \`notification_type\` varchar(32) NOT NULL, \`channel\` varchar(16) NOT NULL, \`recipient_contact\` varchar(255) NOT NULL, \`message_content\` text NOT NULL, \`notification_link\` text NULL, \`retry_count\` int NOT NULL DEFAULT '0', \`last_retry_at\` timestamp NULL, \`status\` varchar(16) NOT NULL, \`sent_at\` timestamp NULL, \`error_message\` text NULL, \`related_orders\` json NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_a724bb8b9955d45f103680beb5\` (\`domain_id\`), PRIMARY KEY (\`notification_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`payments\` (\`payment_id\` char(36) NOT NULL, \`domain_id\` char(36) NOT NULL, \`order_id\` char(36) NOT NULL, \`merchant_id\` char(36) NOT NULL, \`customer_id\` char(36) NOT NULL, \`payment_amount\` decimal(18,4) NOT NULL, \`payment_date\` date NOT NULL, \`payment_method\` varchar(64) NOT NULL, \`payment_proof_url\` text NULL, \`payment_at\` timestamp NULL, \`customer_message\` text NULL, \`status\` varchar(32) NOT NULL, \`verified_by\` char(36) NULL, \`verified_at\` timestamp NULL, \`rejected_by\` char(36) NULL, \`rejected_at\` timestamp NULL, \`reject_reason\` text NULL, \`notes\` text NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_a6810d7849d197ecad59f8622a\` (\`domain_id\`), PRIMARY KEY (\`payment_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`customer_messages\` (\`message_id\` char(36) NOT NULL, \`domain_id\` char(36) NOT NULL, \`customer_id\` char(36) NOT NULL, \`merchant_id\` char(36) NOT NULL, \`order_id\` char(36) NULL, \`message_type\` varchar(16) NOT NULL, \`message_content\` text NOT NULL, \`file_url\` text NULL, \`is_read\` tinyint NOT NULL DEFAULT 0, \`read_at\` timestamp NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_293d62646da47980bc2f70292c\` (\`domain_id\`), PRIMARY KEY (\`message_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD CONSTRAINT \`FK_145532db85752b29c57d2b7b1f1\` FOREIGN KEY (\`order_id\`) REFERENCES \`orders\`(\`order_id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`customer_order_items\` ADD CONSTRAINT \`FK_b9e59e7b59ba5c0c5ab21c851f8\` FOREIGN KEY (\`customer_order_id\`) REFERENCES \`customer_orders\`(\`customer_order_id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`arrival_items\` ADD CONSTRAINT \`FK_a8dbbf82dd0c706e67c8ec7da86\` FOREIGN KEY (\`arrival_id\`) REFERENCES \`arrivals\`(\`arrival_id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`arrival_items\` DROP FOREIGN KEY \`FK_a8dbbf82dd0c706e67c8ec7da86\``);
        await queryRunner.query(`ALTER TABLE \`customer_order_items\` DROP FOREIGN KEY \`FK_b9e59e7b59ba5c0c5ab21c851f8\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP FOREIGN KEY \`FK_145532db85752b29c57d2b7b1f1\``);
        await queryRunner.query(`DROP INDEX \`IDX_293d62646da47980bc2f70292c\` ON \`customer_messages\``);
        await queryRunner.query(`DROP TABLE \`customer_messages\``);
        await queryRunner.query(`DROP INDEX \`IDX_a6810d7849d197ecad59f8622a\` ON \`payments\``);
        await queryRunner.query(`DROP TABLE \`payments\``);
        await queryRunner.query(`DROP INDEX \`IDX_a724bb8b9955d45f103680beb5\` ON \`notifications\``);
        await queryRunner.query(`DROP TABLE \`notifications\``);
        await queryRunner.query(`DROP INDEX \`IDX_9ca7107a9d99099330e90f21d7\` ON \`arrivals\``);
        await queryRunner.query(`DROP TABLE \`arrivals\``);
        await queryRunner.query(`DROP INDEX \`IDX_ea9d95c85f3be48768264c3d7b\` ON \`arrival_items\``);
        await queryRunner.query(`DROP TABLE \`arrival_items\``);
        await queryRunner.query(`DROP INDEX \`IDX_270520ac553e98cb64f9d46a1e\` ON \`customer_orders\``);
        await queryRunner.query(`DROP TABLE \`customer_orders\``);
        await queryRunner.query(`DROP INDEX \`IDX_c1fe570254e16ceaf3d6270d42\` ON \`customer_order_items\``);
        await queryRunner.query(`DROP TABLE \`customer_order_items\``);
        await queryRunner.query(`DROP INDEX \`IDX_06a04a826023e654bcfd58ebff\` ON \`orders\``);
        await queryRunner.query(`DROP TABLE \`orders\``);
        await queryRunner.query(`DROP INDEX \`IDX_06168e79adf9e78a069ecbb5ba\` ON \`order_items\``);
        await queryRunner.query(`DROP TABLE \`order_items\``);
        await queryRunner.query(`DROP INDEX \`IDX_8a26668fda1abe1bd0165f0693\` ON \`exchange_rates\``);
        await queryRunner.query(`DROP INDEX \`IDX_f1a66c537616b14781c4cda78f\` ON \`exchange_rates\``);
        await queryRunner.query(`DROP TABLE \`exchange_rates\``);
        await queryRunner.query(`DROP INDEX \`IDX_77486d71e8f68e188319c8d6ce\` ON \`customers\``);
        await queryRunner.query(`DROP INDEX \`IDX_28a79a3a8385dff6fb94b4c4e9\` ON \`customers\``);
        await queryRunner.query(`DROP TABLE \`customers\``);
        await queryRunner.query(`DROP INDEX \`IDX_ce3bb67cb0926240e65c08cd1b\` ON \`merchants\``);
        await queryRunner.query(`DROP TABLE \`merchants\``);
        await queryRunner.query(`DROP INDEX \`IDX_97672ac88f789774dd47f7c8be\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_b07612fc9ab8c40bf34f0dcfe6\` ON \`users\``);
        await queryRunner.query(`DROP TABLE \`users\``);
        await queryRunner.query(`DROP TABLE \`role_permissions\``);
        await queryRunner.query(`DROP INDEX \`IDX_b2aef658765c9b59c454d56177\` ON \`roles\``);
        await queryRunner.query(`DROP TABLE \`roles\``);
        await queryRunner.query(`DROP INDEX \`IDX_8dad765629e83229da6feda1c1\` ON \`permissions\``);
        await queryRunner.query(`DROP INDEX \`IDX_e18b0544c532dab81b229d0d3b\` ON \`permissions\``);
        await queryRunner.query(`DROP TABLE \`permissions\``);
    }

}
